package com.complaint.model;

public class WnmsCellKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WNMS_CELL.LAC
     *
     * @mbggenerated Thu Mar 07 11:25:27 CST 2013
     */
    private Long lac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WNMS_CELL.CELL_ID
     *
     * @mbggenerated Thu Mar 07 11:25:27 CST 2013
     */
    private Long cellId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WNMS_CELL.LAC
     *
     * @return the value of T_WNMS_CELL.LAC
     *
     * @mbggenerated Thu Mar 07 11:25:27 CST 2013
     */
    public Long getLac() {
        return lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WNMS_CELL.LAC
     *
     * @param lac the value for T_WNMS_CELL.LAC
     *
     * @mbggenerated Thu Mar 07 11:25:27 CST 2013
     */
    public void setLac(Long lac) {
        this.lac = lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WNMS_CELL.CELL_ID
     *
     * @return the value of T_WNMS_CELL.CELL_ID
     *
     * @mbggenerated Thu Mar 07 11:25:27 CST 2013
     */
    public Long getCellId() {
        return cellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WNMS_CELL.CELL_ID
     *
     * @param cellId the value for T_WNMS_CELL.CELL_ID
     *
     * @mbggenerated Thu Mar 07 11:25:27 CST 2013
     */
    public void setCellId(Long cellId) {
        this.cellId = cellId;
    }
}